---
- name: Assign users to ROSA cluster
  hosts: localhost
  gather_facts: no

  tasks:
    - name: 로그인 - OpenShift CLI (oc) 사용
      command: oc login --server={{ rosa_api_url }} --token={{ rosa_token }} 
      register: login_result  # 명령 실행 결과를 저장
      changed_when: false  # 로그인 작업은 변경 사항으로 간주하지 않음

    - name: 사용자 계정 추가
      command: oc create user {{ item }}
      with_items:
        - user1
        - user2
        - user3
      ignore_errors: yes  # 사용자가 이미 존재하는 경우 오류를 무시

    - name: 사용자에게 권한(RoleBinding) 할당  # 역할(Role)을 사용자에게 할당
      command: >
        oc adm policy add-role-to-user {{ item.role }} {{ item.user }} -n {{ item.namespace }}
      with_items:
        - { user: "user1", role: "cluster-admin", namespace: "default" }  # user1 -> 클러스터 관리자
        - { user: "user2", role: "edit", namespace: "dev" }  # user2 -> 개발자(편집 가능)
        - { user: "user3", role: "view", namespace: "prod" }  # user3 -> 읽기 전용
      ignore_errors: yes  # 이미 할당된 경우 오류 무시

    - name: 적용된 사용자 목록 출력
      command: oc get users  # 현재 클러스터에 등록된 사용자 목록 조회
      register: user_list

    - debug:
        msg: "{{ user_list.stdout_lines }}"
