---
- name: Configure network policies in ROSA
  hosts: localhost
  gather_facts: no

  tasks:
    - name: 로그인 - OpenShift CLI (oc) 사용
      command: oc login --server={{ rosa_api_url }} --token={{ rosa_token }} 
      register: login_result
      changed_when: false  # 로그인 작업은 변경사항으로 간주하지 않음

    - name: 네임스페이스 목록 확인  # 현재 클러스터의 네임스페이스 목록을 가져옴
      command: oc get namespaces
      register: ns_list

    - debug:
        msg: "{{ ns_list.stdout_lines }}"  # 네임스페이스 목록 출력

    - name: 기본 네트워크 정책 추가 (외부 접근 차단)
      command: >
        oc apply -f - <<EOF
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: deny-all
          namespace: dev
        spec:
          podSelector: {}  # 네임스페이스 내 모든 Pod에 적용
          policyTypes:
          - Ingress  # 들어오는 트래픽을 제어
          - Egress  # 나가는 트래픽을 제어
          ingress: []  # 모든 외부 트래픽 차단
          egress: []  # 모든 외부 통신 차단
        EOF

    - name: 특정 CIDR 블록 허용 (예: 내부 VPC 서브넷)
      command: >
        oc apply -f - <<EOF
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-vpc-subnet
          namespace: dev
        spec:
          podSelector: {}  # 모든 Pod에 적용
          policyTypes:
          - Ingress  # 외부에서 내부로 들어오는 트래픽 제어
          - Egress  # 내부에서 외부로 나가는 트래픽 제어
          ingress:
          - from:
            - ipBlock:
                cidr: 10.0.0.0/16  # 10.0.0.0/16 대역에서 오는 트래픽 허용
          egress:
          - to:
            - ipBlock:
                cidr: 10.0.0.0/16  # 10.0.0.0/16 대역으로 나가는 트래픽 허용
        EOF
